import CountryComparison from '@/components/country-comparison';
import Link from '@/components/site-link';
import {countryGuides} from '@/data/country-guides';
export const metadata={title:'Doctorados en 31 países: acceso, financiación y condiciones',description:'Compara modelos de doctorado en Europa: admisión, duración, contratos, becas, matrícula, supervisión y defensa. Guías nacionales con fuentes oficiales y fechas.'};
const questions=[
 ['Un doctorado, varias formas de organizarlo','En la vía individual, el acuerdo con la dirección suele ser el punto de partida. En un programa estructurado, una escuela organiza selección, formación y seguimiento. Un doctorado industrial incorpora a una empresa; una cotutela requiere un convenio entre universidades. Son dimensiones que pueden combinarse: “industrial” no dice por sí solo quién paga, y “estructurado” no garantiza financiación.'],
 ['Admisión y financiación: dos decisiones','Antes de aceptar, identifica qué documento has recibido: admisión académica, concesión de una ayuda u oferta de empleo. Comprueba si quedan condiciones pendientes —titulación, visado, selección de proyecto o autorización del financiador— y qué ocurre si solo obtienes una de las dos partes.'],
 ['Cómo comparar una oferta económica','Anota moneda, importe bruto o neto, periodicidad, meses de pago, porcentaje de jornada y años cubiertos. Separa manutención, matrícula, presupuesto de investigación y reembolso de viajes. Después resta tus gastos previsibles. Una ayuda de movilidad o un presupuesto de laboratorio no son dinero libre para vivir.'],
 ['Supervisión y condiciones de trabajo','Pregunta por frecuencia de reuniones, codirección, recursos computacionales, acceso a datos y formación. Revisa carga docente, tareas ajenas a la tesis, criterios de evaluación y vías de mediación o cambio de supervisor. Hablar con doctorandos actuales ayuda a contrastar el funcionamiento cotidiano del grupo.'],
 ['Publicaciones, tesis y defensa','Confirma si se admite monografía o tesis por artículos, qué contribuciones y autorías se exigen, y si los artículos deben estar enviados, aceptados o publicados. Pide las reglas del programa: un número de publicaciones usado en un laboratorio no es necesariamente un requisito nacional. Incluye en tu calendario revisión, depósito, defensa y posibles correcciones.'],
 ['Movilidad y candidatura internacional','Comprueba reconocimiento de títulos, idioma de trabajo, certificados, traducciones y plazos. Después consulta a la oficina internacional y a la autoridad migratoria sobre residencia, permiso de trabajo, seguro y acompañantes. No deduzcas estas condiciones del país o del nombre de la beca; dependen también de nacionalidad, residencia previa y contrato.'],
 ['Plazos, extensiones y vida fuera del laboratorio','Distingue duración prevista, máximo académico y duración financiada. Pide las reglas de enfermedad, cuidados, permiso parental, dedicación parcial y suspensión, y si esas situaciones amplían también el pago. La posibilidad de prorrogar una matrícula no demuestra que haya presupuesto para seguir cobrando.'],
 ['Preparar la solicitud sin perder el foco','Localiza primero el grupo y la línea que te interesan. Revisa el tipo de solicitud: proyecto ya definido, propuesta propia o selección de escuela. Prepara CV académico, expediente, muestra de investigación, motivación y referencias adaptados a los requisitos. Confirma la zona horaria del cierre y el plazo separado que puedan tener quienes envían las referencias.']
];
export default function Page(){return <main id="contenido" className="guide-page wrap"><div className="page-heading"><div><p className="eyebrow">EL DOCTORADO EN EUROPA · 31 PAÍSES</p><h1>El título se parece.<br/>La experiencia cambia.</h1><p>Compara cómo se accede, quién financia, qué formación se exige y cómo se evalúa la tesis. Empieza por dos países o entra directamente en su guía.</p></div><span className="country-stamp" aria-hidden="true">PhD<span>≠ PhD</span></span></div>
 <nav className="guide-jump" aria-label="En esta guía"><a href="#comparar">Comparar países</a><a href="#paises">Todas las guías</a><a href="#preparar">Preparar la decisión</a><a href="#alcance">Fuentes y alcance</a></nav>
 <div className="guide-principles"><div><span>01</span><h3>Admisión y financiación</h3><p>Entrar en un programa no siempre implica recibir un salario o una beca.</p></div><div><span>02</span><h3>La cobertura completa</h3><p>Compara matrícula, manutención, años financiados y condiciones de renovación.</p></div><div><span>03</span><h3>La oferta concreta</h3><p>El marco del país orienta. El contrato y el reglamento determinan tus condiciones.</p></div></div>
 <section id="comparar"><h2 className="compare-heading">Dos países sobre la mesa.</h2><CountryComparison/></section>
 <section id="paises" className="guide-section"><p className="eyebrow">CONSULTA POR PAÍS</p><h2>El contexto, con sus fuentes.</h2><p>Unión Europea, Islandia, Noruega, Reino Unido y Suiza. Cada guía separa el marco nacional de los ejemplos institucionales.</p><div className="country-directory">{countryGuides.map(c=><Link href={'/guia/'+c.code.toLowerCase()} key={c.code}><span>{c.name}</span><span aria-hidden="true">↗</span></Link>)}</div></section>
 <section id="preparar" className="guide-section"><p className="eyebrow">DE LA COMPARACIÓN A LA SOLICITUD</p><h2>Lo que conviene dejar claro.</h2><p>Estas preguntas son una pauta de preparación, no requisitos universales de admisión.</p><div className="guide-questions">{questions.map(([title,body])=><details key={title}><summary>{title}</summary><p>{body}</p></details>)}</div></section>
 <section id="alcance" className="guide-section guide-scope"><h2>Cómo leer esta comparación</h2><p>Usamos las fichas nacionales de Eurydice y fuentes de ministerios, financiadores y universidades. La fecha de consulta no sustituye a la fecha de actualización de la fuente. Cuando una reforma o una diferencia institucional impide generalizar, lo indicamos en la guía.</p><p>La duración académica no equivale a años financiados. No convertimos becas en salarios ni un ejemplo universitario en una norma nacional. Las tasas no confirmadas se presentan como una comprobación pendiente, nunca como cero. Las cifras económicas, cuando aparecen, identifican el financiador y el periodo.</p><p>El alcance geográfico de estas guías es más limitado que el catálogo de oportunidades. <Link className="text-link" href="/fuentes">Consultar cobertura y metodología ↗</Link></p></section>
 </main>;}
