import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
const digest=bytes=>createHash('sha256').update(bytes).digest('hex');
const format='institution-json-shards-v1';
const atomicWrite=async(file,bytes)=>{await fs.writeFile(file+'.tmp',bytes);await fs.rename(file+'.tmp',file);};

// Keep the logical registry unchanged while bounding individual Git objects.
// Legacy snapshots remain readable for old checkouts and migration checks.
export async function readInstitutionRegistry(file='data/institutions.json'){
 for(let attempt=0;attempt<4;attempt++){
  try{
   const manifest=JSON.parse(await fs.readFile(file,'utf8'));
   if(Array.isArray(manifest.institutions))return manifest;
   const {registryStorage:storage,...metadata}=manifest;
   if(storage?.format!==format||!Array.isArray(storage.parts))throw new Error('invalid_registry_storage');
   const prefix=path.basename(file,'.json')+'.parts/';
   const parts=await Promise.all(storage.parts.map(async part=>{
    if(!part.file.startsWith(prefix)||!/^\d{3,}-[a-f0-9]{64}\.json$/.test(part.file.slice(prefix.length)))throw new Error('invalid_registry_part_path');
    const bytes=await fs.readFile(path.join(path.dirname(file),part.file));
    if(digest(bytes)!==part.sha256)throw new Error('registry_part_hash_mismatch');
    const rows=JSON.parse(bytes).institutions;
    if(!Array.isArray(rows)||rows.length!==part.count)throw new Error('registry_part_count_mismatch');
    return rows;
   }));
   const institutions=parts.flat();
   if(institutions.length!==storage.count)throw new Error('registry_count_mismatch');
   return {...metadata,institutions};
  }catch(error){
   // A reader may cross the atomic replacement of a completed crawl snapshot.
   if(attempt===3||!['ENOENT','registry_part_hash_mismatch'].includes(error.code||error.message))throw error;
   await new Promise(resolve=>setTimeout(resolve,50*(attempt+1)));
  }
 }
}

export async function writeInstitutionRegistry(registry,file='data/institutions.json',{maxBytes=4*1024*1024}={}){
 if(!Array.isArray(registry.institutions)||'registryStorage' in registry||!Number.isInteger(maxBytes)||maxBytes<4)throw new Error('invalid_registry');
 const base=path.basename(file,'.json'),directory=path.dirname(file),partsDirectory=base+'.parts';
 const chunks=[];let rows=[],size=20;
 for(const institution of registry.institutions){
  const serialized=JSON.stringify(institution),bytes=Buffer.byteLength(serialized);
  if(bytes+20>maxBytes)throw new Error('institution_exceeds_part_budget');
  if(rows.length&&size+bytes+1>maxBytes){chunks.push(rows);rows=[];size=20;}
  rows.push(serialized);size+=bytes+(rows.length>1?1:0);
 }
 if(rows.length)chunks.push(rows);
 // An object root gives Vite named JSON exports with bounded lines. Top-level
 // arrays become a single enormous line that stalls Vinext's CommonJS scanner.
 const parts=chunks.map((rows,index)=>{const bytes='{"institutions":['+rows.join(',')+']}\n',sha256=digest(bytes);return {file:partsDirectory+'/'+String(index).padStart(3,'0')+'-'+sha256+'.json',count:rows.length,sha256,bytes};});
 await fs.mkdir(path.join(directory,partsDirectory),{recursive:true});
 for(const part of parts)await atomicWrite(path.join(directory,part.file),part.bytes);
 const {institutions,...metadata}=registry;
 const manifest={...metadata,registryStorage:{format,count:institutions.length,parts:parts.map(({bytes,...part})=>part)}};
 await atomicWrite(file,JSON.stringify(manifest)+'\n');
 // Static imports let the Worker bundle keep exactly the same offline fallback.
 const imports=parts.map((part,index)=>`import part${index} from ${JSON.stringify('./'+part.file)} with {type:'json'};`).join('\n');
 const module=`// Generated by registry-storage.mjs; do not edit.\n${imports}\nconst metadata=${JSON.stringify(metadata)};\nconst institutions=[${parts.map((_,index)=>'part'+index+'.institutions').join(',')}].flat();\nif(institutions.length!==${institutions.length})throw new Error('registry_count_mismatch');\nexport default {...metadata,institutions};\n`;
 await atomicWrite(path.join(directory,base+'.snapshot.mjs'),module);
 const current=new Set(parts.map(part=>path.basename(part.file)));
 for(const name of await fs.readdir(path.join(directory,partsDirectory)))if(/^\d{3,}-[a-f0-9]{64}\.json$/.test(name)&&!current.has(name))await fs.unlink(path.join(directory,partsDirectory,name));
 return {institutions:institutions.length,parts:parts.length,maxPartBytes:Math.max(0,...parts.map(part=>Buffer.byteLength(part.bytes)))};
}
