import Link from "@/components/site-link";
import { ArrowUpRight, ArrowRight, Search } from "lucide-react";
import {getCatalogue} from '@/lib/catalogue';
import {statusOf,dateLabel,COUNTRY_NAMES} from '@/lib/types';

const stages=[
{id:"grado",name:"Dar el primer paso",level:"Durante el grado",description:"Estancias de verano, ayudantías y primeros proyectos con un grupo de investigación.",tag:"Experiencia"},
{id:"master",name:"Aprender a investigar",level:"Máster de investigación",description:"Programas con tesis, trabajo de laboratorio y una vía hacia el doctorado.",tag:"Formación"},
{id:"doctorado",name:"Hacer tu propia pregunta",level:"Doctorado",description:"Proyectos y escuelas doctorales. Con contrato, beca o financiación por confirmar.",tag:"Investigación"},
{id:"postdoc",name:"Abrir una línea",level:"Postdoctorado",description:"Contratos y fellowships para construir una agenda de investigación independiente.",tag:"Independencia"},
{id:"faculty",name:"Construir un grupo",level:"Carrera académica",description:"Plazas docentes, tenure track y liderazgo de equipos de investigación.",tag:"Consolidación"}];
export default async function Home(){const data=await getCatalogue();const live=data.records.filter(r=>['open','rolling','listed'].includes(statusOf(r)));const due=live.filter(r=>r.deadline&&Date.parse(r.deadline)-Date.now()<30*86400000).sort((a,b)=>Date.parse(a.deadline!)-Date.parse(b.deadline!));const countries=new Set(live.map(r=>r.country));const programmes=data.records.filter(r=>statusOf(r)==='programme'&&r.stage==='master'&&!r.kind.includes('funding'));return <>

<main id="contenido"><section className="hero wrap"><div className="hero-copy"><p className="eyebrow">UN ATLAS PARA LA VIDA ACADÉMICA · EUROPA</p><h1>Tu siguiente<br/>pregunta merece<br/><em>un lugar.</em></h1><p className="hero-intro">De tu primer proyecto a tu propio grupo. Encuentra dónde investigar, cómo llegar y con qué financiarlo.</p><Link className="primary-button" href="/explorar"><Search size={18}/> Explorar oportunidades <ArrowUpRight size={18}/></Link><p className="scope-note">Ciencia de datos · Machine learning · Estadística<br/>Informática · Matemáticas aplicadas</p></div>
<div className="route-notebook"><div className="notebook-heading"><span className="eyebrow">NO HAY UN ÚNICO CAMINO</span><span className="folio">FIG. 01</span></div><div className="route-diagram">{stages.map((s,i)=><Link href={'/explorar?etapa='+s.id} className={'route-stop stop-'+i} key={s.id}><span className="stop-number">0{i+1}</span><span><small>{s.level}</small><strong>{s.name}</strong></span><ArrowUpRight size={17}/></Link>)}</div><div className="notebook-foot"><span>La financiación atraviesa todas las etapas.</span><Link href="/financiacion">Ver becas <ArrowRight size={16}/></Link></div></div></section>
<div className="discipline-strip"><div className="wrap"><span>UNA DISCIPLINA, MUCHOS CAMINOS</span><span>Datos</span><span>Aprendizaje</span><span>Estadística</span><span>Computación</span><span>Matemáticas</span></div></div>
<section className="journey-section wrap" id="recorrido"><div className="section-heading"><div><p className="eyebrow">EMPIEZA DONDE ESTÁS</p><h2>¿En qué punto te encuentras?</h2></div><p>Cada etapa tiene sus oportunidades.<br/>Y sus propias reglas de entrada.</p></div><div className="stage-grid">{stages.map((s,i)=><Link href={'/explorar?etapa='+s.id} className={'stage-card stage-'+s.id} key={s.id}><div className="stage-card-top"><span>0{i+1}</span><ArrowUpRight size={21}/></div><p className="stage-level">{s.level}</p><h3>{s.name}</h3><p>{s.description}</p><span className="stage-tag">{s.tag}</span></Link>)}</div></section>
<section className="catalogue-window wrap"><div className="section-heading"><div><p className="eyebrow">UNA VISTA DEL CATÁLOGO</p><h2>Del mapa a una posibilidad.</h2></div><p>Comprobado el {dateLabel(data.generatedAt)}.<br/><Link href="/fuentes">Ver el alcance de esta edición ↗</Link></p></div><div className="catalogue-signals"><Link href="/explorar"><strong>{live.length}</strong><span>vacantes con plazo abierto<br/>o publicadas sin fecha</span><ArrowUpRight/></Link><Link href="/explorar"><strong>{countries.size}</strong><span>países europeos<br/>con vacantes en el índice</span><ArrowUpRight/></Link><Link href="/explorar?etapa=master"><strong>{programmes.length}</strong><span>másteres con investigación<br/>documentada</span><ArrowUpRight/></Link></div><div className="deadline-window"><div><p className="eyebrow">PARA MIRAR CON TIEMPO</p><h3>{due.length} anuncios cierran<br/>en los próximos 30 días.</h3><p>Empieza por el proyecto y la supervisión. Después, compara las condiciones.</p><Link className="text-link" href="/explorar">Consultar los próximos cierres <ArrowRight size={17}/></Link></div><div>{due.slice(0,3).map(r=><Link className="deadline-row" key={r.id} href={'/oportunidad/'+r.id}><span>{dateLabel(r.deadline)}</span><div><small>{r.institution} · {COUNTRY_NAMES[r.country]}</small><h3>{r.title}</h3></div><ArrowUpRight size={19}/></Link>)}</div></div></section><section className="country-teaser wrap"><div className="country-stamp">PhD<br/><span>≠ PhD</span></div><div><p className="eyebrow">ANTES DE ELEGIR UN PAÍS</p><h2>El mismo título.<br/>Condiciones muy distintas.</h2><p>Un contrato de trabajo y una beca de manutención cambian lo que debes comparar. Revisa salario, matrícula, duración y requisitos de cada oferta.</p><Link className="text-link" href="/guia">Entender el doctorado en Europa <ArrowUpRight size={18}/></Link></div><aside><p className="eyebrow">EL CATÁLOGO, CON CONTEXTO</p><p>Una fecha de revisión. Una fuente original. Una distinción clara entre un programa y una convocatoria abierta.</p><Link href="/fuentes">Cómo comprobamos la información <ArrowRight size={16}/></Link></aside></section></main>
</>;}
