import Link from '@/components/site-link';
import {ArrowUpRight,ArrowRight} from 'lucide-react';
import {getCatalogue} from '@/lib/catalogue';
import {dateLabel} from '@/lib/types';
import './home.css';
const startingPoints=[
  {id:'grado',label:'Desde el grado',title:'Quiero probar la investigación',body:'TFG, estancias, escuelas de verano y un máster que te acerque a una pregunta.'},
  {id:'master',label:'Durante o después del máster',title:'Quiero dar el siguiente paso',body:'Un TFM con recorrido, grupos donde encajar y vías de acceso al doctorado.'},
  {id:'trabajo',label:'Desde el trabajo',title:'Me planteo volver a investigar',body:'Cómo usar tu experiencia, revisar el acceso y preparar una transición viable.'},
  {id:'preparado',label:'Con experiencia investigadora',title:'Busco un doctorado financiado',body:'Proyecto, dirección, contrato y candidatura: cuatro piezas que deben encajar.'},
];
export default async function Home(){
  const catalogue=await getCatalogue();
  const spanish=catalogue.records.filter(record=>!record.kind.includes('funding')&&(record.country==='ES'||record.destinationCountries?.includes('ES'))).length;
  const funding=catalogue.records.filter(record=>record.kind==='funding-programme').length;
  return <main id="contenido">
    <section className="hero doctoral-hero wrap">
      <div className="hero-copy"><p className="eyebrow">PENSAR EN UN DOCTORADO · DESDE ESPAÑA</p><h1>Tu curiosidad<br/>puede ser<br/><em>el principio.</em></h1><p className="hero-intro">Investigar se aprende. Encuentra cómo probarlo, preparar tu perfil y dar el salto a un doctorado con condiciones que encajen contigo.</p><Link className="primary-button" href="/mi-camino">Encontrar mi siguiente paso <ArrowUpRight size={18}/></Link><Link className="home-secondary" href="/doctorado-en-espana">Entender primero cómo funciona ↗</Link><p className="scope-note">Para quien vive en España y mira hacia la investigación.<br/>Datos · IA · Estadística · Informática · Matemáticas aplicadas</p></div>
      <div className="doctoral-notebook"><div className="notebook-heading"><p className="eyebrow">ANTES DE ENVIAR UNA SOLICITUD</p><span className="folio">CUADERNO 01</span></div><p className="notebook-title">Tres preguntas.<br/>Tu propio camino.</p><ol><li><span>01</span><div><Link href="/doctorado-en-espana#decidir">¿Me gusta investigar?<ArrowUpRight size={18}/></Link><p>Prueba una pregunta, un proyecto, un grupo.</p></div></li><li><span>02</span><div><Link href="/doctorado-en-espana#acceso">¿Qué necesito para entrar?<ArrowUpRight size={18}/></Link><p>Titulación, experiencia y encaje con la línea.</p></div></li><li><span>03</span><div><Link href="/doctorado-en-espana#financiacion">¿Cómo lo hago sostenible?<ArrowUpRight size={18}/></Link><p>Financiación, tiempo y condiciones de trabajo.</p></div></li></ol><div className="notebook-foot"><span>Ni una única ruta,<br/>ni una decisión para siempre.</span><Link href="/mi-camino">Abrir mi plan <ArrowRight size={16}/></Link></div></div>
    </section>
    <section className="home-start wrap" id="recorrido"><div className="section-heading"><div><p className="eyebrow">EMPIEZA DONDE ESTÁS</p><h2>No todo el mundo llega por el mismo sitio.</h2></div><p>Elige tu punto de partida.<br/>Después ajusta tu plan.</p></div><div className="home-start-grid">{startingPoints.map((point,index)=><Link key={point.id} href={'/mi-camino?situacion='+point.id+'&objetivo='+(point.id==='preparado'?'solicitar':point.id==='master'?'experiencia':'decidir')}><div><span>0{index+1}</span><ArrowUpRight size={20}/></div><p className="eyebrow">{point.label}</p><h3>{point.title}</h3><p>{point.body}</p></Link>)}</div></section>
    <section className="home-route wrap"><div><p className="eyebrow">EL CONTEXTO ESPAÑOL, CON SUS MATICES</p><h2>De “me lo planteo”<br/>a saber qué hacer.</h2><p>Grado y máster oficial, TFG y TFM, escuela doctoral, contratos vinculados a proyectos, FPU, ayudas autonómicas y becas. Entiende qué papel cumple cada pieza y quién debe confirmar tus requisitos.</p><Link className="text-link" href="/doctorado-en-espana">Leer la guía desde España <ArrowUpRight size={18}/></Link></div><div className="home-guide-links"><Link href="/doctorado-en-espana#grupo"><span>Elegir bien</span><strong>Un grupo, una dirección y una forma de trabajar.</strong><ArrowUpRight size={20}/></Link><Link href="/doctorado-en-espana#candidatura"><span>Preparar la candidatura</span><strong>Qué mostrar y cómo escribir a un posible supervisor.</strong><ArrowUpRight size={20}/></Link><Link href="/guia?pais1=ES&pais2=GB"><span>Mirar fuera</span><strong>Compara España con otros modelos de doctorado.</strong><ArrowUpRight size={20}/></Link></div></section>
    <section className="home-catalogue wrap"><div className="section-heading"><div><p className="eyebrow">OPORTUNIDADES CON UNA FUENTE DETRÁS</p><h2>Ahora, ponle nombres a tu plan.</h2></div><p>Edición del {dateLabel(catalogue.generatedAt)}.<br/><Link href="/fuentes">Cobertura y límites ↗</Link></p></div><div className="home-catalogue-links"><Link href="/explorar?pais=ES"><h3>Investigar en España <ArrowUpRight size={19}/></h3><p>Másteres, experiencias y vacantes. Usa los filtros para separar etapa y vigencia.</p><span>{spanish.toLocaleString('es-ES')} fichas con destino España en el archivo</span></Link><Link href="/financiacion?etapa=doctorado"><h3>Financiar el siguiente paso <ArrowUpRight size={19}/></h3><p>Ayudas para estudiar o investigar aquí y fuera. Distingue destino y entidad financiadora.</p><span>{funding.toLocaleString('es-ES')} programas de financiación en el catálogo</span></Link><Link href="/programas"><h3>Ganar experiencia <ArrowUpRight size={19}/></h3><p>Estancias y escuelas de verano con ediciones documentadas. Prepara la siguiente convocatoria.</p><span>Consulta requisitos, costes y calendario</span></Link></div><p className="home-archive-note">El catálogo conserva todas sus etapas, incluidos postdoc y carrera académica. Una ficha documentada no implica una convocatoria abierta. <Link href="/explorar?vigencia=all">Explorar todo el archivo ↗</Link></p></section>
    <section className="home-closing wrap"><p className="eyebrow">LO QUE IMPORTA ES EL ENCAJE</p><h2>No necesitas decidir toda tu carrera hoy.</h2><p>Empieza por un paso que te ayude a conocer mejor la investigación.</p><Link className="primary-button" href="/mi-camino">Preparar mi camino <ArrowUpRight size={17}/></Link></section>
  </main>;
}
