'use client';
import {useState} from 'react';
import Link from '@/components/site-link';
import {ArrowUpRight} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {countryGuides,GUIDE_VERIFIED} from '@/data/country-guides';
import {dateLabel} from '@/lib/types';
export default function CountryComparison(){const [left,setLeft]=useState('GB'),[right,setRight]=useState('CH');const choices=[countryGuides.find(c=>c.code===left)!,countryGuides.find(c=>c.code===right)!];const rows=[['model','Relación con la institución'],['pay','Cómo se financia'],['fees','Matrícula y otros costes'],['duration','Duración y cobertura'],['admission','Cómo se accede'],['watch','La pregunta importante']] as const;return <><div className="country-pickers">{[[left,setLeft,'Primer país'],[right,setRight,'Segundo país']].map(([value,setter,label])=><div key={String(label)}><label>{String(label)}</label><Select value={String(value)} onValueChange={setter as (s:string)=>void}><SelectTrigger aria-label={String(label)}><SelectValue/></SelectTrigger><SelectContent>{countryGuides.map(c=><SelectItem value={c.code} key={c.code}>{c.name}</SelectItem>)}</SelectContent></Select></div>)}</div><p className="mobile-table-hint">Desliza la tabla para ver ambos países.</p><div className="country-comparison"><Table><TableHeader><TableRow><TableHead>Qué comparar</TableHead>{choices.map((c,i)=><TableHead key={i}><span className="country-code">{c.code}</span><h2>{c.name}</h2><p>{c.example}</p></TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(([key,title])=><TableRow key={key}><TableCell>{title}</TableCell>{choices.map((c,i)=><TableCell key={i}>{c[key]}</TableCell>)}</TableRow>)}<TableRow><TableCell>Fuentes consultadas</TableCell>{choices.map((c,i)=><TableCell key={i}>{c.sources.map(s=><a href={s.url} target="_blank" rel="noreferrer" key={s.url}>{s.title}<ArrowUpRight size={14}/></a>)}</TableCell>)}</TableRow></TableBody></Table></div><p className="guide-date">Revisión editorial: {dateLabel(GUIDE_VERIFIED)}. Son patrones y ejemplos institucionales, no condiciones universales por país.</p><div className="guide-actions"><Link href="/explorar?etapa=doctorado" className="primary-button">Explorar doctorados <ArrowUpRight size={17}/></Link><Link href="/financiacion?etapa=doctorado" className="text-link">Buscar financiación doctoral <ArrowUpRight size={17}/></Link></div></>}
