'use client';
import {lazy,Suspense,useCallback,useDeferredValue,useEffect,useMemo,useRef,useState} from 'react';
import Link from './site-link';
import {Search,ArrowRight,RefreshCw,X,Scale,ArrowUpRight} from 'lucide-react';
import {OpportunityCard} from './opportunity-card';
import {STAGES,FIELDS,COUNTRY_NAMES,dateLabel,type Opportunity} from '@/lib/types';
import {defaults,readFilters,filterQuery,selectRecords,researchMetric,isRanked,SUBJECTS,type Filters,type SearchData} from '@/lib/search';
import {loadIndex,loadDetails} from '@/lib/web-data';
const Comparison=lazy(()=>import('./comparison-dialog'));
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(s:string)=>void;options:readonly (readonly [string,string])[]}){return <label className="filter-choice"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>;}
const emptyData:SearchData={generatedAt:null,researchGeneratedAt:null,records:[],institutions:{}};
export default function Explorer({funding=false}:{funding?:boolean}){
 const [data,setData]=useState<SearchData>(emptyData),[f,setF]=useState<Filters>(defaults),[loaded,setLoaded]=useState(false),[refreshing,setRefreshing]=useState(true),[error,setError]=useState(false),[detailResult,setDetailResult]=useState({key:"",revision:0,errors:[] as string[]|null}),[detailRevision,setDetailRevision]=useState(0),[details,setDetails]=useState<Record<string,Opportunity>>({}),[compare,setCompare]=useState<string[]>([]),[dialog,setDialog]=useState(false);
 const indexRequest=useRef({version:0}),lastDetailRevision=useRef(0),pageFocus=useRef(false),resultsHeading=useRef<HTMLDivElement>(null),comparisonButton=useRef<HTMLButtonElement>(null);
 const query=useDeferredValue(f.q);
 const fetchIndex=useCallback((fresh=true)=>{const request=++indexRequest.current.version;return loadIndex<SearchData>(funding?'funding':'explorer',fresh).then(updated=>{if(!Array.isArray(updated.records)||!updated.institutions)throw new Error();if(request!==indexRequest.current.version)return;setData(updated);setCompare(ids=>ids.filter(id=>updated.records.some(record=>record.id===id)));setLoaded(true);setError(false);if(fresh)setDetailRevision(v=>v+1);}).catch(()=>{if(request===indexRequest.current.version)setError(true);}).finally(()=>{if(request===indexRequest.current.version)setRefreshing(false);});},[funding]);
 const refresh=useCallback((fresh=true)=>{setRefreshing(true);void fetchIndex(fresh);},[fetchIndex]);
 useEffect(()=>{const requestState=indexRequest.current;const sync=()=>setF(readFilters(new URLSearchParams(location.search)));sync();window.addEventListener('popstate',sync);void fetchIndex(false);const timer=setInterval(()=>void refresh(true),300000);return()=>{requestState.version++;clearInterval(timer);window.removeEventListener('popstate',sync);};},[fetchIndex,refresh]);
 useEffect(()=>{if(!loaded)return;const url=new URL(location.href);url.search=filterQuery(f).toString();history.replaceState(null,'',url);},[f,loaded]);
 const change=(key:keyof Filters,value:string)=>setF(v=>({...v,[key]:value,page:1}));
 const reset=()=>{setF({...defaults});setCompare([]);};
 const filtered=useMemo(()=>selectRecords(data,{...f,q:query}),[data,f,query]);
 const pages=Math.max(1,Math.ceil(filtered.length/12)),page=Math.min(f.page,pages),visible=filtered.slice((page-1)*12,page*12);
 // Clamp this component’s own state before committing an out-of-range URL.
 if(loaded&&f.page!==page)setF({...f,page});
 const recordById=useMemo(()=>new Map(data.records.map(r=>[r.id,r])),[data]);
 const detailKey=[...new Set([...visible.map(r=>r.detailPath),...compare.map(id=>recordById.get(id)?.detailPath).filter((path):path is string=>Boolean(path))])].join('|');
 // Reset completion when the requested paths change, including an A → B → A retry.
 if(detailResult.key!==detailKey||detailResult.revision!==detailRevision)setDetailResult({key:detailKey,revision:detailRevision,errors:null});
 const detailsLoading=Boolean(detailKey&&detailResult.errors===null);
 const detailErrors=detailKey?detailResult.errors||[]:[];
 useEffect(()=>{if(!detailKey)return;let active=true;const fresh=lastDetailRevision.current!==detailRevision;lastDetailRevision.current=detailRevision;void loadDetails(detailKey.split('|'),fresh).then(({records,failedPaths})=>{if(active){setDetails(v=>({...v,...records}));setDetailResult({key:detailKey,revision:detailRevision,errors:failedPaths});}});return()=>{active=false;};},[detailKey,detailRevision]);
 useEffect(()=>{if(pageFocus.current){pageFocus.current=false;resultsHeading.current?.focus({preventScroll:true});resultsHeading.current?.scrollIntoView({block:'start'});}},[page]);
 const goToPage=(next:number)=>{pageFocus.current=true;setF(v=>({...v,page:next}));};
 const countries=useMemo(()=>[...new Set(data.records.map(r=>r.country))].sort((a,b)=>(COUNTRY_NAMES[a]||a).localeCompare(COUNTRY_NAMES[b]||b,'es')),[data]);
 const eligible=useMemo(()=>data.records.filter(r=>f.stage==='all'||r.stage===f.stage||r.eligibleStages?.includes(f.stage as Opportunity['stage'])),[data,f.stage]);
 const ranked=eligible.filter(r=>isRanked(researchMetric(r,data,f.subject))).length,currentStage=STAGES.find(s=>s.id===f.stage);
 const selected=compare.map(id=>details[recordById.get(id)?.detailPath||'']).filter(Boolean),toggle=(id:string)=>setCompare(v=>v.includes(id)?v.filter(x=>x!==id):v.length<3&&details[recordById.get(id)?.detailPath||'']?[...v,id]:v);
 const closeComparison=()=>setDialog(false);
 const advanced=['kind','status','funding','language','closing'].filter(key=>f[key as keyof Filters]!==defaults[key as keyof Filters]).length;
 return <main id="contenido" className="explorer-page wrap"><div className="page-heading"><div><p className="eyebrow">{funding?'RECURSOS PARA SEGUIR INVESTIGANDO':'EL ÍNDICE DE OPORTUNIDADES'}</p><h1>{funding?'El tiempo para investigar\ntambién se financia.':'Encuentra tu próximo lugar.'}</h1><p>Filtra las condiciones y compara la fortaleza investigadora de las instituciones en tu disciplina.</p></div><div className="edition-note"><span className="eyebrow">EDICIÓN DEL CATÁLOGO</span><strong>{data.generatedAt?dateLabel(data.generatedAt):error?'Edición no disponible':'Cargando edición…'}</strong><Link href="/fuentes">Ver cobertura <ArrowUpRight size={14}/></Link></div></div>
 <nav className="stage-navigation" aria-label="Etapa académica">{[{id:'all',short:'Todas las etapas'},...STAGES].map(s=><button key={s.id} aria-pressed={f.stage===s.id} onClick={()=>change('stage',s.id)}>{s.short}</button>)}</nav>
 <div className="stage-context"><strong>{currentStage?.label||'Tu recorrido, a tu ritmo'}</strong><p>{currentStage?.intro||'Programas, convocatorias y financiación con sus fuentes. Una institución sin tier no recibe una valoración baja.'}</p></div>
 <div className="search-box"><Search size={21}/><input aria-label="Buscar oportunidades" value={f.q} onChange={e=>change('q',e.target.value)} placeholder="Tema, universidad o varias palabras clave…"/>{f.q&&<button aria-label="Borrar búsqueda" onClick={()=>change('q','')}><X size={18}/></button>}</div>
 <div className="filters-row primary-filters"><Choice label="País" value={f.country} onChange={v=>change('country',v)} options={[['all','Todos los países'],...countries.map(c=>[c,COUNTRY_NAMES[c]||c] as const)]}/><Choice label="Área del programa" value={f.field} onChange={v=>change('field',v)} options={[['all','Todas las áreas'],...FIELDS.map(s=>[s,s] as const)]}/><Choice label="Prestigio en" value={f.subject} onChange={v=>change('subject',v)} options={SUBJECTS}/><Choice label="Tier investigador" value={f.tier} onChange={v=>change('tier',v)} options={[['all','Todos, incluidos sin tier'],['T1','T1 · 10 % superior'],['T1T2','T1 + T2 · 25 % superior'],['T2','T2'],['T3','T3'],['T4','T4'],['ranked','Con tier calculado'],['unranked','Sin tier calculado']]}/></div>
 <details className="advanced-filters" open={advanced>0||undefined}><summary>Más filtros{advanced?' · '+advanced+(advanced===1?' activo':' activos'):''}</summary><div className="filters-row"><Choice label="Tipo" value={f.kind} onChange={v=>change('kind',v)} options={[['all','Vacantes y programas'],['position','Vacantes'],['programme','Programas'],...(!funding?[['master-programme','Programas de máster'] as const]:[])]}/><Choice label="Vigencia" value={f.status} onChange={v=>change('status',v)} options={[['current','Abiertas y programas'],['open','Solo plazo abierto'],['rolling','Admisión continua'],['programme','Programas'],['listed','Publicadas sin fecha'],['unverified','Por confirmar'],['closed','Plazo cerrado'],['all','Todo el archivo']]}/><Choice label="Financiación" value={f.funding} onChange={v=>change('funding',v)} options={[['all','Cualquier financiación'],['salary','Salario o contrato'],['scholarship','Beca o estipendio'],['waiver','Exención de matrícula'],['grant','Ayuda o subvención'],['mixed','Financiación mixta'],['unconfirmed','Sin financiación confirmada']]}/><Choice label="Idioma mencionado" value={f.language} onChange={v=>change('language',v)} options={[['all','Cualquier idioma'],['english','Inglés'],['spanish','Español'],['french','Francés'],['german','Alemán']]}/><Choice label="Cierre en" value={f.closing} onChange={v=>change('closing',v)} options={[['all','Cualquier plazo'],['7','Próximos 7 días'],['30','Próximos 30 días'],['90','Próximos 90 días']]}/></div><p className="small muted">El idioma es una mención en los requisitos; confirma si toda la docencia se imparte en él. Una ayuda condicionada no garantiza financiación.</p></details>
 <div className="search-method"><p>Prestigio investigador = actividad e impacto en <strong>{SUBJECTS.find(s=>s[0]===f.subject)?.[1]}</strong>. {loaded?`${ranked.toLocaleString('es-ES')} de ${eligible.length.toLocaleString('es-ES')} registros de esta etapa tienen tier.`:''} Los que carecen de datos aparecen al final al ordenar por indicadores. <Link href={'/instituciones?disciplina='+f.subject+'#metodo-tiers'}>Ver método y fuentes</Link>.</p><button className="reset-filters" onClick={reset}>Limpiar filtros</button></div>
 <div className="results-heading" ref={resultsHeading} tabIndex={-1} aria-label="Resultados de la búsqueda"><p role="status" aria-live="polite"><strong>{loaded?filtered.length.toLocaleString('es-ES'):'…'}</strong> {filtered.length===1?'resultado':'resultados'}</p><Choice label="Ordenar" value={f.sort} onChange={v=>change('sort',v)} options={[['prestige','Prestigio investigador'],['impact','Impacto: proporción top 10 %'],['volume','Actividad investigadora'],['deadline','Próximo cierre'],['recent','Última comprobación'],['institution','Institución A–Z'],['title','Título A–Z']]}/></div>
 {error&&<p className="notice" role="alert">No se ha podido cargar la edición.{loaded?' Se conservan los resultados anteriores.':''} <button className="text-link" onClick={()=>void refresh(true)} disabled={refreshing}>{refreshing?'Reintentando…':'Reintentar'}</button></p>}
 {!loaded&&!error&&<p className="loading-results" role="status">Cargando el índice de oportunidades…</p>}
 {detailErrors.length>0&&<p className="notice" role="alert">Algunas condiciones no se pudieron cargar. Las demás fichas siguen disponibles. <button className="text-link" disabled={detailsLoading} onClick={()=>setDetailRevision(v=>v+1)}>{detailsLoading?'Reintentando…':'Reintentar condiciones'}</button> También puedes abrir la ficha completa.</p>}
 {loaded&&(filtered.length?<div className="opportunity-grid">{visible.map(r=><OpportunityCard key={r.id} record={details[r.detailPath]||({...r,entry:'',funding:{...r.funding,text:''}})} loading={!details[r.detailPath]} unavailable={detailErrors.includes(r.detailPath)} research={r.researchInstitutionId?data.institutions[r.researchInstitutionId]:undefined} subject={f.subject} selected={compare.includes(r.id)} onCompare={toggle} compareDisabled={!compare.includes(r.id)&&(!details[r.detailPath]||compare.length>=3)}/>)}</div>:<div className="empty-results"><Search size={32}/><h2>No hay coincidencias con estos filtros.</h2><p>Amplía los tiers, países o condiciones. Que no aparezca aquí no implica que la oportunidad no exista.</p><button className="primary-button" onClick={reset}>Ampliar la búsqueda</button></div>)}
 {loaded&&pages>1&&<nav className="results-pagination" aria-label="Páginas de resultados"><button disabled={page===1} onClick={()=>goToPage(page-1)}>Anterior</button><span>Página {page} de {pages}</span><button disabled={page===pages} onClick={()=>goToPage(page+1)}>Siguiente <ArrowRight size={16}/></button></nav>}
 <div className="catalogue-footnote"><p>Cada filtro queda guardado en la dirección de la página. Actualizar consulta descarga la última edición publicada.</p><button onClick={()=>void refresh(true)} disabled={refreshing}><RefreshCw size={14} className={refreshing?'spin':''}/>{refreshing?'Actualizando…':'Actualizar consulta'}</button></div>
 {compare.length>0&&<div className="compare-tray"><Scale size={21}/><span>{compare.length} de 3 seleccionadas</span><button ref={comparisonButton} className="primary-button" onClick={()=>setDialog(true)} disabled={selected.length<2}>Comparar condiciones</button><button aria-label="Vaciar comparación" onClick={()=>setCompare([])}><X size={20}/></button></div>}
 {dialog&&<Suspense fallback={<p role="status">Abriendo comparación…</p>}><Comparison selected={selected} onClose={closeComparison} onRestoreFocus={()=>comparisonButton.current?.focus()}/></Suspense>}
 </main>;
}
