'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import Link from '@/components/site-link';
import {Search,ArrowRight,RefreshCw,X,Scale,ArrowUpRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import {OpportunityCard} from './opportunity-card';
import {STAGES,FIELDS,COUNTRY_NAMES,dateLabel,statusOf,type Opportunity} from '@/lib/types';
import type {ExplorerCatalogue} from '@/lib/explorer-data';
const normalize=(s:string)=>s.toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(s:string)=>void;options:[string,string][]}){return <div className="filter-choice"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent position="popper">{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select></div>}
export default function Explorer({initial,initialStage='all',funding=false,initialQuery=''}:{initial:string;initialStage?:string;funding?:boolean;initialQuery?:string}){
 // One JSON string avoids serializing thousands of nested RSC props while
 // preserving server-rendered results. Parse once; refreshes use the listing API.
 const [data,setData]=useState<ExplorerCatalogue>(()=>JSON.parse(initial)),[stage,setStage]=useState(initialStage),[query,setQuery]=useState(initialQuery),[country,setCountry]=useState('all'),[field,setField]=useState('all'),[kind,setKind]=useState('all'),[status,setStatus]=useState('current'),[sort,setSort]=useState('deadline'),[page,setPage]=useState(1),[compare,setCompare]=useState<string[]>([]),[dialog,setDialog]=useState(false),[refreshing,setRefreshing]=useState(false),[refreshError,setRefreshError]=useState(false);
 const refresh=useCallback(async()=>{setRefreshing(true);try{const r=await fetch('/api/explorer'+(funding?'?funding=1':''),{signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error();const updated=await r.json() as ExplorerCatalogue;if(!Array.isArray(updated.records))throw new Error();setData(updated);setRefreshError(false);}catch{setRefreshError(true);}finally{setRefreshing(false);}},[funding]);
 useEffect(()=>{const t=setInterval(refresh,300000);return()=>clearInterval(t);},[refresh]);
 useEffect(()=>{setPage(1);const url=new URL(location.href);if(stage==='all')url.searchParams.delete('etapa');else url.searchParams.set('etapa',stage);if(query)url.searchParams.set('q',query);else url.searchParams.delete('q');history.replaceState(null,'',url);},[stage,query,country,field,kind,status,sort]);
 const base=useMemo(()=>data.records.filter(r=>funding?r.kind.includes('funding'):!r.kind.includes('funding')),[data,funding]);
 const eligible=base.filter(r=>stage==='all'||r.stage===stage||r.eligibleStages?.includes(stage as import('@/lib/types').Stage));
 const countries=[...new Set(base.map(r=>r.country))].sort((a,b)=>(COUNTRY_NAMES[a]||a).localeCompare(COUNTRY_NAMES[b]||b,'es'));
 const filtered=eligible.filter(r=>(!query||normalize([r.title,r.institution,r.city,COUNTRY_NAMES[r.country],...r.fields].join(' ')).includes(normalize(query)))&&(country==='all'||r.country===country)&&(field==='all'||r.fields.includes(field))&&(kind==='all'||(kind==='programme'?r.kind.includes('programme'):r.kind==='position'))&&(status==='all'||(status==='current'?!['closed','unverified'].includes(statusOf(r)):statusOf(r)===status))).sort((a,b)=>sort==='institution'?a.institution.localeCompare(b.institution):sort==='recent'?Date.parse(b.verifiedAt||'0')-Date.parse(a.verifiedAt||'0'):(a.deadline?Date.parse(a.deadline):Infinity)-(b.deadline?Date.parse(b.deadline):Infinity));
 const open=eligible.filter(r=>['open','rolling'].includes(statusOf(r)));const salaried=open.filter(r=>r.funding.kind==='salary');const due=open.filter(r=>r.deadline&&Date.parse(r.deadline)-Date.now()<=30*86400000);const pages=Math.ceil(filtered.length/12);const currentStage=STAGES.find(s=>s.id===stage);const selected=data.records.filter(r=>compare.includes(r.id));
 const programmeCount=eligible.filter(r=>statusOf(r)==='programme').length;const groupCount=new Set(eligible.map(r=>r.institution)).size;const countryCount=new Set(eligible.filter(r=>r.country!=='EU').map(r=>r.country)).size;const programmeView=funding||stage==='master';
 const toggle=(id:string)=>setCompare(v=>v.includes(id)?v.filter(x=>x!==id):v.length<3?[...v,id]:v);
 const reset=()=>{setStage('all');setQuery('');setCountry('all');setField('all');setKind('all');setStatus('current');setPage(1);};
 return <main id="contenido" className="explorer-page wrap"><div className="page-heading"><div><p className="eyebrow">{funding?'RECURSOS PARA SEGUIR INVESTIGANDO':'EL ÍNDICE DE OPORTUNIDADES'}</p><h1>{funding?'El tiempo para investigar\ntambién se financia.':'Encuentra tu próximo lugar.'}</h1><p>{funding?'Becas, ayudas de movilidad y programas de financiación. Revisa la nacionalidad, la residencia y el destino exigidos en cada convocatoria.':'Vacantes y programas en Europa. Filtra por tu etapa y compara las condiciones que importan.'}</p></div><div className="edition-note"><span className="eyebrow">ÚLTIMO BARRIDO</span><strong>{dateLabel(data.generatedAt)}</strong><Link href="/fuentes">Ver cobertura <ArrowUpRight size={14}/></Link></div></div>
 <Tabs value={stage} onValueChange={setStage} className="stage-tabs"><TabsList variant="line" aria-label="Etapa académica"><TabsTrigger value="all">Todas las etapas</TabsTrigger>{STAGES.map(s=><TabsTrigger value={s.id} key={s.id}><span>{s.number}</span>{s.short}</TabsTrigger>)}</TabsList>{['all',...STAGES.map(s=>s.id)].map(id=><TabsContent value={id} key={id}><div className="stage-context"><span className="eyebrow">{currentStage?currentStage.label:'TU RECORRIDO, A TU RITMO'}</span><p>{currentStage?.intro||'Empieza por una etapa o explora el conjunto. Las fichas separan las convocatorias abiertas de los programas que debes consultar.'}</p></div></TabsContent>)}</Tabs>
 <div className="insight-strip"><div><strong>{programmeView?programmeCount:open.length}</strong><span>{programmeView?'programas verificados':'con plazo abierto o admisión continua'}</span></div><div><strong>{programmeView?groupCount:salaried.length}</strong><span>{programmeView?'instituciones y financiadores':'indican remuneración o contrato'}</span></div><div><strong>{programmeView?countryCount:due.length}</strong><span>{programmeView?'países representados':'cierran en los próximos 30 días'}</span></div><p>Sobre la etapa seleccionada.<br/><Link href="/fuentes">La cobertura aún está creciendo.</Link></p></div>
 <div className="search-box"><Search size={21}/><input aria-label="Buscar oportunidades" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tema, universidad o palabra clave…"/>{query&&<button aria-label="Borrar búsqueda" onClick={()=>setQuery('')}><X size={18}/></button>}</div>
 <div className="filters-row"><Choice label="País" value={country} onChange={setCountry} options={ [['all','Todos los países'],...countries.map(c=>[c,COUNTRY_NAMES[c]||c] as [string,string])]}/><Choice label="Disciplina" value={field} onChange={setField} options={[['all','Todas las disciplinas'],...FIELDS.map(f=>[f,f] as [string,string])]}/><Choice label="Tipo" value={kind} onChange={setKind} options={[['all','Vacantes y programas'],['position','Vacantes'],['programme','Programas']]}/><Choice label="Vigencia" value={status} onChange={setStatus} options={[['current','Abiertas y programas'],['open','Solo plazo abierto'],['programme','Programas'],['listed','Publicadas sin fecha'],['unverified','Por confirmar'],['closed','Plazo cerrado'],['all','Todo el archivo']]}/><button className="reset-filters" onClick={reset}>Limpiar filtros</button></div>
 <div className="results-heading"><p role="status" aria-live="polite"><strong>{filtered.length}</strong> {filtered.length===1?'resultado':'resultados'}</p><Choice label="Ordenar" value={sort} onChange={setSort} options={[['deadline','Próximo cierre'],['recent','Última comprobación'],['institution','Institución']]}/></div>
 {refreshError&&<p className="notice" role="status">No se ha podido actualizar la consulta. Se conserva el catálogo cargado.</p>}
 {filtered.length?<div className="opportunity-grid">{filtered.slice((page-1)*12,page*12).map(r=><OpportunityCard key={r.id} record={r} selected={compare.includes(r.id)} onCompare={toggle} compareDisabled={compare.length>=3&&!compare.includes(r.id)}/>)}</div>:<div className="empty-results"><Search size={32}/><h2>No hay coincidencias en el catálogo.</h2><p>Prueba otro tema o amplía los filtros. Que no aparezca aquí no implica que la oportunidad no exista.</p><button className="primary-button" onClick={reset}>Ampliar la búsqueda</button><Link href="/fuentes">Consultar las fuentes originales <ArrowUpRight size={16}/></Link></div>}
 {pages>1&&<Pagination className="results-pagination" aria-label="Páginas de resultados"><PaginationContent><PaginationItem><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Anterior</button></PaginationItem><PaginationItem><span>Página {page} de {pages}</span></PaginationItem><PaginationItem><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Siguiente <ArrowRight size={16}/></button></PaginationItem></PaginationContent></Pagination>}
 <div className="catalogue-footnote"><p>Fecha y requisitos proceden de la fuente enlazada. Las convocatorias pueden cambiar entre comprobaciones. {data.mode==='snapshot'?'Se muestra la última copia disponible.':''}</p><button onClick={refresh} disabled={refreshing}><RefreshCw size={14} className={refreshing?'spin':''}/>{refreshing?'Actualizando…':'Actualizar consulta'}</button></div>
 {compare.length>0&&<div className="compare-tray"><Scale size={21}/><span>{compare.length} de 3 seleccionadas</span><button className="primary-button" onClick={()=>setDialog(true)} disabled={compare.length<2}>Comparar condiciones</button><button aria-label="Vaciar comparación" onClick={()=>setCompare([])}><X size={20}/></button></div>}
 <Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="comparison-dialog" showCloseButton={false}><DialogClose className="dialog-close" aria-label="Cerrar comparación"><X/></DialogClose><DialogTitle>Las condiciones, una junto a otra.</DialogTitle><DialogDescription>Los importes conservan su moneda y periodo originales; bruto y neto no son equivalentes.</DialogDescription><Table><TableHeader><TableRow><TableHead>Condición</TableHead>{selected.map(r=><TableHead key={r.id}>{r.institution}<Link href={'/oportunidad/'+r.id}>{r.title}</Link></TableHead>)}</TableRow></TableHeader><TableBody>{[['País',(r:Opportunity)=>COUNTRY_NAMES[r.country]],['Nivel de entrada',(r:Opportunity)=>r.entry],['Financiación',(r:Opportunity)=>r.funding.text],['Duración',(r:Opportunity)=>r.duration||'Por confirmar en la convocatoria'],['Contrato',(r:Opportunity)=>r.contract||'No confirmado'],['Matrícula',(r:Opportunity)=>r.feeNote||'Consultar la fuente'],['Cierre',(r:Opportunity)=>dateLabel(r.deadline)],['Comprobado',(r:Opportunity)=>dateLabel(r.verifiedAt)]].map(([name,value])=><TableRow key={String(name)}><TableCell>{String(name)}</TableCell>{selected.map(r=><TableCell key={r.id}>{(value as (r:Opportunity)=>string)(r)}</TableCell>)}</TableRow>)}</TableBody></Table></DialogContent></Dialog>
 </main>;
}
