'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from '@/components/site-link';
import {ArrowUpRight,Search} from 'lucide-react';
import {INSTITUTION_COUNTRIES,RESEARCH_SUBJECTS,normaliseInstitutionQuery,type InstitutionRow,type InstitutionMetadata} from '@/lib/institutions';
import {loadIndex} from '@/lib/web-data';
import {descendingMetric} from '@/lib/search';
import {sitePath} from '@/lib/site-path';
import {InstitutionSources} from './institution-sources';
import {dateLabel} from '@/lib/types';
const n=(v:number)=>v.toLocaleString('es-ES');
export default function Institutions({registry,counts}:{registry:InstitutionMetadata;counts:Record<string,number>}){
 const [all,setAll]=useState<InstitutionRow[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(false),[loading,setLoading]=useState(true),[params,setParams]=useState<URLSearchParams>(new URLSearchParams());
 const request=useRef({version:0});
 const fetchRows=useCallback((fresh=false)=>{const version=++request.current.version;return loadIndex<InstitutionRow[]>('institutions',fresh).then(rows=>{if(!Array.isArray(rows))throw new Error('Inventario no disponible');if(version!==request.current.version)return;setAll(rows);setLoaded(true);setError(false);}).catch(()=>{if(version===request.current.version)setError(true);}).finally(()=>{if(version===request.current.version)setLoading(false);});},[]);
 useEffect(()=>{const requestState=request.current;const sync=()=>setParams(new URLSearchParams(location.search));sync();window.addEventListener('popstate',sync);void fetchRows();return()=>{requestState.version++;window.removeEventListener('popstate',sync);};},[fetchRows]);
 const countries=[...new Set([...registry.scope.countries,...registry.scope.transcontinental,...(registry.scope.academicExtension||[])])].sort((a,b)=>(INSTITUTION_COUNTRIES[a]||a).localeCompare(INSTITUTION_COUNTRIES[b]||b,'es'));
 const q=(params.get('q')||'').slice(0,200),country=countries.includes(params.get('pais')||'')?params.get('pais')!:'',scope=['prioridad','fuentes','todo'].includes(params.get('vista')||'')?params.get('vista')!:'prioridad',subject=RESEARCH_SUBJECTS.some(s=>s.id===params.get('disciplina'))?params.get('disciplina')!:'cs',tier=['T1','T2','T3','T4','pendiente'].includes(params.get('tier')||'')?params.get('tier')!:'',order=['prestige','impact','volume','name'].includes(params.get('orden')||'')?params.get('orden')!:'prestige';
 const query=normaliseInstitutionQuery(q);
 const filtered=all.filter(i=>(!country||i.country===country)&&(!query||normaliseInstitutionQuery([i.name,...i.aliases,i.city].join(' ')).includes(query))&&(scope==='todo'||(scope==='fuentes'?i.sourceCount>0:i.priority))&&(!tier||(tier==='pendiente'?!i.researchMetrics[subject]?.tier:i.researchMetrics[subject]?.tier===tier)));
 filtered.sort((a,b)=>{const am=a.researchMetrics[subject],bm=b.researchMetrics[subject],key=order==='impact'?'top10Share':order==='volume'?'volume':'score';return (order==='name'?0:Number(Boolean(bm?.tier))-Number(Boolean(am?.tier))||(am?.tier&&bm?.tier?descendingMetric(am[key],bm[key]):0))||a.name.localeCompare(b.name,'es')||a.id.localeCompare(b.id);});
 const total=filtered.length,pageCount=Math.max(1,Math.ceil(total/25)),requestedPage=Number(params.get('pagina')||1),page=Number.isSafeInteger(requestedPage)?Math.min(pageCount,Math.max(1,requestedPage)):1,rows=filtered.slice((page-1)*25,page*25);

 const href=(changes:Record<string,string>)=>{const params=new URLSearchParams({q,pais:country,vista:scope,disciplina:subject,tier,orden:order,...changes});for(const [key,v] of [...params])if(!v)params.delete(key);return '/instituciones?'+params.toString()+'#resultados-instituciones';};
 const metricInfo=registry.research?.subjects.find(x=>x.id===subject);
 return <main id="contenido" className="institutions-page wrap">
  <div className="page-heading"><div><p className="eyebrow">EL MAPA SE RECORRE INSTITUCIÓN POR INSTITUCIÓN</p><h1>Dónde se investiga.<br/>Qué queda por encontrar.</h1><p>Universidades, centros y financiadores de toda Europa. Sigue sus fuentes oficiales y compara los indicadores de investigación en la disciplina que te interesa.</p></div></div>
  <div className="coverage-stats"><div><strong>{n(registry.summary.total)}</strong><span>entidades en el inventario de búsqueda</span></div><div><strong>{n(registry.summary.withSources)}</strong><span>con fuentes académicas localizadas</span></div><div><strong>{n(registry.summary.withCheckedSources)}</strong><span>con alguna fuente leída</span></div><div><strong>{n(registry.summary.countriesWithSources)}</strong><span>países y territorios con fuentes</span></div></div>
  <p className="notice">El inventario incluye entidades pendientes de revisar y de confirmar en estas materias. Cada institución puede ofrecer muchos programas. Una fuente leída todavía puede tener programas por descubrir. <Link href="/explorar">Ver oportunidades comprobadas ↗</Link></p>
  {registry.crawl&&<p className="small muted">Rastreo automático: {n(registry.crawl.statuses.read||0)} páginas leídas de {n(registry.crawl.jobs)} en la cola de búsqueda. {n(registry.crawl.statuses.pending||0)} pendientes de lectura; {n(registry.crawl.statuses['access-pending']||0)} con acceso pendiente. Los enlaces descubiertos todavía necesitan revisión antes de convertirse en oportunidades.</p>}
  {<p className="small muted">Mostrando la copia guardada del inventario, de {dateLabel(registry.generatedAt)}.</p>}
  <form className="institution-filters" method="get" action={sitePath("/instituciones#resultados-instituciones")} key={[q,country,scope,subject,tier,order].join("|")}>
   <label className="institution-search"><span>Buscar institución</span><div><Search size={17}/><input name="q" defaultValue={q} maxLength={200} placeholder="Nombre, siglas o ciudad"/></div></label>
   <label><span>País o territorio</span><select name="pais" defaultValue={country}><option value="">Todos</option>{countries.map(c=><option key={c} value={c}>{INSTITUTION_COUNTRIES[c]||c}</option>)}</select></label>
   <label><span>Inventario</span><select name="vista" defaultValue={scope}><option value="prioridad">Fuentes y actividad detectadas</option><option value="fuentes">Con fuentes localizadas</option><option value="todo">Todo, incluido pendiente</option></select></label>
   <label><span>Disciplina de los indicadores</span><select name="disciplina" defaultValue={subject}>{RESEARCH_SUBJECTS.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
   <label><span>Tier orientativo</span><select name="tier" defaultValue={tier}><option value="">Todos</option>{['T1','T2','T3','T4'].map(x=><option key={x} value={x}>{x}</option>)}<option value="pendiente">Sin tier calculado</option></select></label>
   <label><span>Ordenar por</span><select name="orden" defaultValue={order}><option value="prestige">Prestigio investigador</option><option value="impact">Impacto de citas</option><option value="volume">Actividad científica</option><option value="name">Nombre</option></select></label>
   <button className="primary-button" type="submit">Aplicar filtros</button><Link className="text-link" href="/instituciones">Restablecer</Link>
  </form>
  {!loaded&&!error&&<p className="notice" role="status">Cargando el inventario institucional…</p>}{error&&<p className="notice" role="alert">No se pudo cargar el inventario.{loaded?' Se conserva la copia anterior.':''} <button className="text-link" onClick={()=>{setLoading(true);void fetchRows(true);}} disabled={loading}>{loading?'Reintentando…':'Reintentar'}</button></p>}
  <div className="institution-results-heading" id="resultados-instituciones" tabIndex={-1}><p role="status" aria-live="polite"><strong>{loaded?n(total):'…'}</strong> {total===1?'institución':'instituciones'} · página {page} de {pageCount}</p><a className="text-link" href="#metodo-tiers">Cómo se calculan los tiers ↓</a></div>
  {!metricInfo&&<p className="notice">Los indicadores de {RESEARCH_SUBJECTS.find(x=>x.id===subject)?.name||'esta disciplina'} están pendientes de completar. La ausencia de tier no es una valoración baja.</p>}
  <div className="institution-list">{rows.map(i=>{const metric=i.researchMetrics[subject];return <article key={i.id} className="institution-row"><div className="institution-identity"><p className="eyebrow">{INSTITUTION_COUNTRIES[i.country]||i.country}{i.city?' · '+i.city:''}</p><h2>{i.officialUrl?<a href={i.officialUrl} target="_blank" rel="noreferrer">{i.name}<ArrowUpRight size={16}/></a>:i.name}</h2><p className="small muted">{i.sourceCount?`${i.sourceCount} fuentes localizadas · ${i.checkedSourceCount} leídas`:'Fuentes académicas pendientes de localizar'}</p>{i.crawl&&i.crawl.read>0&&<p className="small muted">Recorrido automático: {n(i.crawl.read)} páginas leídas · {n(i.crawl.pending)} pendientes. Inventario de programas aún en revisión.</p>}{i.geography==='campus-review'&&<p className="institution-geography">País transcontinental: la ubicación europea del campus requiere comprobación antes de incorporar sus oportunidades.</p>}{i.geography==='ehea-extension'&&<p className="institution-geography">Ampliación académica del Espacio Europeo de Educación Superior: el país se identifica por separado del ámbito geográfico europeo.</p>}{i.geographyNote&&<p className="small muted">{i.geographyNote}</p>}{i.ror&&<a className="small text-link" href={i.ror} target="_blank" rel="noreferrer">Identidad ROR ↗</a>}</div>
   <div className="institution-metrics"><strong className={'tier-mark '+(metric?.tier?'':'tier-pending')}>{metric?.tier||'Sin tier'}</strong>{metric?.openalexId&&typeof metric.volume==='number'?<>{typeof metric.score==='number'&&<p><b>{metric.score.toFixed(1)}/100</b> · índice investigador</p>}<p><b>{n(metric.volume||0)}</b> publicaciones · 2020–2024</p><p>{metric.top10Share==null?'Impacto sin datos suficientes':`${(metric.top10Share*100).toFixed(1).replace('.',',')} % en el 10 % más citado`}</p><p className="small muted">Impacto: {metric.impactEligible==null?'denominador no disponible':`${n(metric.impactEligible)} trabajos de 2020–2022`}{metric.reason==='small-sample'?' · muestra insuficiente':metric.reason==='citation-coverage'?' · cobertura insuficiente':metric.reason==='geography-pending'?' · geografía pendiente':''}</p><a className="small text-link" href={metric.openalexId} target="_blank" rel="noreferrer">Registro OpenAlex ↗</a></>:<p className="small muted">Indicadores aún no disponibles para esta institución y disciplina.</p>}</div>
   {i.sourcePath&&<InstitutionSources path={i.sourcePath}/>}
  </article>;})}</div>
  {loaded&&!rows.length&&<p className="notice">Todavía no hay instituciones con estos filtros. Prueba «Todo, incluido pendiente» para consultar el inventario completo del país.</p>}
  <nav className="institution-pagination" aria-label="Páginas de instituciones">{page>1&&<Link href={href({pagina:String(page-1)})}>← Anterior</Link>}<span>{page} / {pageCount}</span>{page<pageCount&&<Link href={href({pagina:String(page+1)})}>Siguiente →</Link>}</nav>
  <section className="institution-method" id="metodo-tiers"><p className="eyebrow">INDICADORES, DATOS Y LÍMITES</p><h2>La fortaleza depende de la disciplina.</h2><p>Los tiers son una agrupación bibliométrica orientativa de TRAMA. Combinan actividad científica e impacto de citas. No miden la calidad de la supervisión, las condiciones de trabajo ni tus posibilidades de admisión. Ciencia de datos es transversal: consulta informática, IA y estadística según tu línea.</p>
   <details open><summary>La regla de cálculo</summary><p>Actividad: publicaciones de 2020–2024. Impacto: proporción de trabajos de 2020–2022 que OpenAlex sitúa en el 10 % más citado, normalizado por tipo, año y subdisciplina. Incluimos artículos, ponencias completas de congresos y artículos de datos y software; no añadimos preprints como una segunda publicación.</p><p>Exigimos al menos 50 publicaciones de actividad, 50 trabajos con impacto calculable y una cobertura de impacto del 80 %. Comparamos el percentil de actividad y el percentil del límite inferior de Wilson al 95 % de la proporción más citada. Ambos pesan un 50 %. Ordenamos ese resultado dentro de las instituciones elegibles del ámbito descrito: T1 corresponde al 10 % superior; T2 al siguiente 15 %; T3 al siguiente 25 %; T4 al resto. Los empates conservan el mismo percentil medio. Los datos insuficientes quedan sin tier.</p></details>
   <details><summary>Qué se compara y qué puede faltar</summary><p>El universo parte de entidades educativas activas en ROR y de centros añadidos mediante revisión institucional. Los trabajos se asignan por su tema principal y por afiliación exacta de OpenAlex; no sumamos automáticamente filiales al organismo matriz. Una publicación compartida cuenta una vez para cada institución participante. Los temas de IA y visión se solapan con informática.</p><p>Los registros, las afiliaciones y las citas pueden contener errores. La indexación es desigual entre idiomas y disciplinas. Rusia, Turquía y Kazajistán entran como candidatos con ubicación del campus pendiente; no reciben tier europeo automáticamente. Chipre se incluye en el ámbito académico europeo. Armenia, Azerbaiyán y Georgia se incorporan como ampliación académica explícita por su pertenencia al <a href="https://ehea.info/about-ehea/ehea-membership-and-criteria/" target="_blank" rel="noreferrer">Espacio Europeo de Educación Superior</a>. Solo se calcula su tier cuando la consulta incluye expresamente esos países. El inventario incorpora países pequeños y territorios, aunque aún no tengan fuentes revisadas.</p></details>
   <details><summary>Fuentes y fecha de esta edición</summary><p>Registro institucional: <a href={registry.provenance.url} target="_blank" rel="noreferrer">ROR · edición de {dateLabel(registry.provenance.releaseDate)}</a>. Datos bajo CC0. Registro de TRAMA actualizado el {dateLabel(registry.generatedAt)}.</p><p>Bibliometría: <a href="https://help.openalex.org/data/works/citations/" target="_blank" rel="noreferrer">método de citas de OpenAlex</a> y <a href="https://help.openalex.org/data/work-types/" target="_blank" rel="noreferrer">tipos de publicación</a>. Solo se calculan tiers cuando termina la descarga de todos los grupos de la disciplina.</p>{registry.research?.subjects.map(s=><p key={s.id}>{s.name}: {n(s.cohortSize)} instituciones con muestra suficiente. {(s.references.volume.urls||[s.references.volume.url]).map((url,index)=><a key={url} href={url} target="_blank" rel="noreferrer">{index?' · Congresos, datos y software':'Actividad: artículos'}</a>)} · {(s.references.top10.urls||[s.references.top10.url]).map((url,index)=><a key={url} href={url} target="_blank" rel="noreferrer">{index?' · Congresos, datos y software':'Impacto: artículos'}</a>)} · comprobación {dateLabel(s.references.volume.checkedAt)}.</p>)}</details>
  </section>
  <section className="institution-country-coverage"><h2>País por país, lo que falta.</h2><p>Los recuentos de oportunidades describen el catálogo actual. Una casilla vacía señala trabajo pendiente.</p><div className="institution-coverage-grid">{countries.map(c=>{const coverage=registry.summary.countries[c]||{total:0,withSources:0};return <Link href={href({pais:c,vista:'todo',pagina:'1',q:'',tier:''})} key={c}><strong>{INSTITUTION_COUNTRIES[c]||c}</strong><span>{n(coverage.total)} entidades · {n(coverage.withSources)} con fuentes</span><span>{n(counts[c]||0)} oportunidades en el catálogo</span></Link>;})}</div></section>
 </main>;
}
