import {COUNTRY_NAMES} from './types';
export type ResearchMetric={openalexId:string|null;volume:number|null;impactTotal:number|null;impactEligible:number|null;top10:number|null;top10Share:number|null;impactCoverage:number|null;tier:string|null;reason:string|null;score?:number;percentile?:number;cohortSize?:number};
export type InstitutionSource={id:string;type:string;url:string;label:string;status:string;checkedAt:string|null;observedAt:string;contentHash:string|null;lastError:string|null};
export type Institution={id:string;ror:string|null;name:string;aliases:string[];country:string;city:string|null;officialUrl:string|null;geography:string;geographyNote?:string;reviewStatus:string;sources:InstitutionSource[];researchMetrics:Record<string,ResearchMetric>;crawl?:{queued:number;read:number;pending:number;documents:number;lastCheckedAt:string|null;complete:boolean}};
export type InstitutionRegistry={generatedAt:string;provenance:{url:string;releaseDate:string;version:string;license:string};scope:{countries:string[];transcontinental:string[];academicExtension?:string[];academicExtensionSource?:string};institutions:Institution[];crawl?:{jobs:number;statuses:Record<string,number>;institutionsRead:number;updatedAt:string;lastRun:{attempted:number;read:number;failed:number;discovered:number}};research?:{generatedAt:string;status:string;activityWindow:number[];impactWindow:number[];workTypes?:string[];subjects:{id:string;name:string;taxonomy:string[];countryScope?:string[];cohortSize:number;references:Record<string,{url:string;urls?:string[];checkedAt:string;pages:number;groups:number}>}[]}};
export type InstitutionMetadata=Omit<InstitutionRegistry,'institutions'>&{summary:{total:number;withSources:number;withCheckedSources:number;countriesWithSources:number;countries:Record<string,{total:number;withSources:number;withCheckedSources:number}>}};
export const INSTITUTION_COUNTRIES:Record<string,string>={...COUNTRY_NAMES,BY:'Bielorrusia',RU:'Rusia',TR:'Turquía',KZ:'Kazajistán',VA:'Ciudad del Vaticano',AX:'Åland',FO:'Islas Feroe',GG:'Guernsey',GI:'Gibraltar',IM:'Isla de Man',JE:'Jersey',SJ:'Svalbard y Jan Mayen'};
export const RESEARCH_SUBJECTS=[{id:'cs',name:'Informática'},{id:'ml',name:'IA y aprendizaje automático'},{id:'statistics',name:'Estadística y probabilidad'},{id:'applied-math',name:'Matemáticas aplicadas'}];
export const normaliseInstitutionQuery=(s:string)=>s.normalize('NFKD').replace(/\p{M}/gu,'').toLowerCase();
export const sourceKind:Record<string,string>={masters:'Másteres',phd:'Doctorados',funding:'Financiación',jobs:'Plazas',research:'Investigación'};


export type InstitutionRow=Omit<Institution,'sources'>&{sourceCount:number;checkedSourceCount:number;priority:boolean;sourcePath:string|null};
