export type Stage='grado'|'master'|'doctorado'|'postdoc'|'faculty';
export type Opportunity={id:string;kind:string;stage:Stage;eligibleStages?:Stage[];title:string;institution:string;country:string;city?:string|null;url:string;applyUrl:string;sourceId:string;sourceName:string;verifiedAt:string|null;seenAt:string;deadline:string|null;deadlinePrecision?:string|null;status:string;fields:string[];funding:{kind:string;text:string;amount?:number|null;currency?:string|null;period?:string|null;gross?:boolean};duration?:string|null;entry:string;languages:string[];contract?:string|null;hours?:string|null;researchNote?:string;eligibilityNote?:string;feeNote?:string;programmeType?:string;evidence?:{contentHash?:string;checkedUrl:string;method:string;researchUrl?:string};lastError?:string|null;};
export type Source={id:string;name:string;url:string;adapter:string;type:string;scope:string;stages:string[];enabled:boolean;status?:string;note?:string;report?:{checkedAt?:string;pages?:number;accepted?:number;complete?:boolean;errors?:{url?:string;error:string}[]}};
export type Catalogue={generatedAt:string|null;records:Opportunity[];sources:Source[];run:{id:string;startedAt:string;finishedAt:string|null;status:string;sources?:unknown[]}|null;mode?:'live'|'snapshot';};
export const STAGES:{id:Stage;label:string;short:string;number:string;intro:string;benefit:string}[]=[
{id:'grado',label:'Primeras experiencias',short:'Primeros pasos',number:'01',intro:'Estancias, ayudantías y puestos de apoyo a la investigación. Comprueba el nivel de acceso: algunos exigen haber terminado el grado o el máster.',benefit:'Busca supervisión, un proyecto definido y resultados que puedas documentar: una contribución técnica, una presentación o una referencia académica.'},
{id:'master',label:'Másteres de investigación',short:'Máster',number:'02',intro:'Másteres por investigación y programas con tesis o proyectos supervisados. El formato y el peso de la investigación se indican en cada ficha.',benefit:'La tesis, el grupo que la supervisa y la formación en métodos son más informativos para una futura carrera académica que el nombre del programa.'},
{id:'doctorado',label:'Doctorados',short:'Doctorado',number:'03',intro:'Compara proyectos con vacante y programas doctorales. La admisión al programa y la financiación pueden requerir solicitudes distintas.',benefit:'Revisa el encaje con la línea y la supervisión, la duración financiada, la matrícula y el tipo de relación con la universidad.'},
{id:'postdoc',label:'Postdoctorados',short:'Postdoc',number:'04',intro:'Contratos de investigación después del doctorado y fellowships para desarrollar una línea propia.',benefit:'Valora la autonomía científica, las oportunidades de colaboración, el acceso a recursos y el tiempo disponible para publicar.'},
{id:'faculty',label:'Carrera académica',short:'Carrera académica',number:'05',intro:'Plazas docentes e investigadoras, tenure track y puestos para dirigir una agenda de investigación.',benefit:'Compara estabilidad, evaluación para la promoción, carga docente, recursos iniciales y capacidad de supervisar doctorandos.'}];
export const COUNTRY_NAMES:Record<string,string>={AT:'Austria',BE:'Bélgica',BG:'Bulgaria',HR:'Croacia',CY:'Chipre',CZ:'Chequia',DK:'Dinamarca',EE:'Estonia',FI:'Finlandia',FR:'Francia',DE:'Alemania',GR:'Grecia',HU:'Hungría',IS:'Islandia',IE:'Irlanda',IT:'Italia',LV:'Letonia',LT:'Lituania',LU:'Luxemburgo',MT:'Malta',NL:'Países Bajos',NO:'Noruega',PL:'Polonia',PT:'Portugal',RO:'Rumanía',SK:'Eslovaquia',SI:'Eslovenia',ES:'España',SE:'Suecia',CH:'Suiza',GB:'Reino Unido',AL:'Albania',BA:'Bosnia y Herzegovina',ME:'Montenegro',MK:'Macedonia del Norte',RS:'Serbia',UA:'Ucrania',MD:'Moldavia',XK:'Kosovo',LI:'Liechtenstein',MC:'Mónaco',AD:'Andorra',SM:'San Marino',EU:'Varios países europeos'};
export const FIELDS=['Ciencia de datos','Machine learning','Estadística','Informática','Matemáticas aplicadas'];
export function statusOf(r:Opportunity,now=Date.now()){if(r.status==='closed')return 'closed';if(r.deadline&&Date.parse(r.deadline.length===10?r.deadline+'T23:59:59Z':r.deadline)<now)return 'closed';if(r.lastError)return 'unverified';if(r.kind==='programme'||r.kind==='funding-programme')return 'programme';if(!r.verifiedAt||now-Date.parse(r.verifiedAt)>14*86400000)return 'unverified';if(r.deadline)return 'open';return ['rolling','listed'].includes(r.status)?r.status:'unverified';}
export const STATUS_NAMES:Record<string,string>={open:'Plazo abierto',listed:'Publicada · sin fecha',rolling:'Admisión continua',programme:'Programa · consultar convocatoria',closed:'Plazo cerrado',unverified:'Vigencia por confirmar'};
export function dateLabel(value?:string|null){return value?new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Madrid'}).format(new Date(value)):'Sin fecha publicada';}
